include: package:jaspr_repo/analysis_options.yaml

analyzer:
  exclude:
    - tool/scaffold/**
    - tool/templates/**
  errors:
    deprecated_member_use: ignore # TODO: remove when upgrading to analyzer 8

linter:
  rules:
    # Disabled so that we can group dependencies semantically.
    sort_pub_dependencies: false
