name: flutter_embedding_demo
description: A demo of embedding a flutter app into a jaspr website.
version: 0.1.6
publish_to: none

environment:
  sdk: '>=3.0.0-0 <4.0.0'

dependencies:
  firebase_core: ^3.4.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  jaspr: ^0.19.0
  jaspr_flutter_embed: ^0.4.6
  jaspr_riverpod: ^0.3.20
  riverpod: ^2.4.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  jaspr_builder: ^0.16.3
  jaspr_web_compilers: ^4.0.10

flutter:
  uses-material-design: true
  assets:
    - assets/dash.png

jaspr:
  mode: server
